willingness_to_pay_by_region = {
    "North America": 150,
    "Other Americas": 0,
    "Europe": 150,
    "Asia": 0,
    "Africa": 0,
    "Oceania": 0,
    "Middle East": 0,
}

iso3_to_wp_region_dict = {
    "AFG": "Asia",
    "ALA": "Europe",
    "ALB": "Europe",
    "DZA": "Africa",
    "ASM": "Oceania",
    "AND": "Europe",
    "AGO": "Africa",
    "AIA": "Other Americas",
    "ATA": "",
    "ATG": "Other Americas",
    "ARG": "Other Americas",
    "ARM": "Asia",
    "ABW": "Other Americas",
    "AUS": "Oceania",
    "AUT": "Europe",
    "AZE": "Asia",
    "BHS": "Other Americas",
    "BHR": "Asia",
    "BGD": "Asia",
    "BRB": "Other Americas",
    "BLR": "Europe",
    "BEL": "Europe",
    "BLZ": "Other Americas",
    "BEN": "Africa",
    "BMU": "Other Americas",
    "BTN": "Asia",
    "BOL": "Other Americas",
    "BES": "Other Americas",
    "BIH": "Europe",
    "BWA": "Africa",
    "BVT": "Other Americas",
    "BRA": "Other Americas",
    "IOT": "Africa",
    "BRN": "Asia",
    "BGR": "Europe",
    "BFA": "Africa",
    "BDI": "Africa",
    "CPV": "Africa",
    "KHM": "Asia",
    "CMR": "Africa",
    "CAN": "North America",
    "CYM": "Other Americas",
    "CAF": "Africa",
    "TCD": "Africa",
    "CHL": "Other Americas",
    "CHN": "Asia",
    "CXR": "Oceania",
    "CCK": "Oceania",
    "COL": "Other Americas",
    "COM": "Africa",
    "COG": "Africa",
    "COD": "Africa",
    "COK": "Oceania",
    "CRI": "Other Americas",
    "CIV": "Africa",
    "HRV": "Europe",
    "CUB": "Other Americas",
    "CUW": "Other Americas",
    "CYP": "Asia",
    "CZE": "Europe",
    "DNK": "Europe",
    "DJI": "Africa",
    "DMA": "Other Americas",
    "DOM": "Other Americas",
    "ECU": "Other Americas",
    "EGY": "Africa",
    "SLV": "Other Americas",
    "GNQ": "Africa",
    "ERI": "Africa",
    "EST": "Europe",
    "SWZ": "Africa",
    "ETH": "Africa",
    "FLK": "Other Americas",
    "FRO": "Europe",
    "FJI": "Oceania",
    "FIN": "Europe",
    "FRA": "Europe",
    "GUF": "Other Americas",
    "PYF": "Oceania",
    "ATF": "Africa",
    "GAB": "Africa",
    "GMB": "Africa",
    "GEO": "Asia",
    "DEU": "Europe",
    "GHA": "Africa",
    "GIB": "Europe",
    "GRC": "Europe",
    "GRL": "Other Americas",
    "GRD": "Other Americas",
    "GLP": "Other Americas",
    "GUM": "Oceania",
    "GTM": "Other Americas",
    "GGY": "Europe",
    "GIN": "Africa",
    "GNB": "Africa",
    "GUY": "Other Americas",
    "HTI": "Other Americas",
    "HMD": "Oceania",
    "VAT": "Europe",
    "HND": "Other Americas",
    "HKG": "Asia",
    "HUN": "Europe",
    "ISL": "Europe",
    "IND": "Asia",
    "IDN": "Asia",
    "IRN": "Asia",
    "IRQ": "Asia",
    "IRL": "Europe",
    "IMN": "Europe",
    "ISR": "Asia",
    "ITA": "Europe",
    "JAM": "Other Americas",
    "JPN": "Asia",
    "JEY": "Europe",
    "JOR": "Asia",
    "KAZ": "Asia",
    "KEN": "Africa",
    "KIR": "Oceania",
    "PRK": "Asia",
    "KOR": "Asia",
    "KWT": "Asia",
    "KGZ": "Asia",
    "LAO": "Asia",
    "LVA": "Europe",
    "LBN": "Asia",
    "LSO": "Africa",
    "LBR": "Africa",
    "LBY": "Africa",
    "LIE": "Europe",
    "LTU": "Europe",
    "LUX": "Europe",
    "MAC": "Asia",
    "MDG": "Africa",
    "MWI": "Africa",
    "MYS": "Asia",
    "MDV": "Asia",
    "MLI": "Africa",
    "MLT": "Europe",
    "MHL": "Oceania",
    "MTQ": "Other Americas",
    "MRT": "Africa",
    "MUS": "Africa",
    "MYT": "Africa",
    "MEX": "Other Americas",
    "FSM": "Oceania",
    "MDA": "Europe",
    "MCO": "Europe",
    "MNG": "Asia",
    "MNE": "Europe",
    "MSR": "Other Americas",
    "MAR": "Africa",
    "MOZ": "Africa",
    "MMR": "Asia",
    "NAM": "Africa",
    "NRU": "Oceania",
    "NPL": "Asia",
    "NLD": "Europe",
    "NCL": "Oceania",
    "NZL": "Oceania",
    "NIC": "Other Americas",
    "NER": "Africa",
    "NGA": "Africa",
    "NIU": "Oceania",
    "NFK": "Oceania",
    "MKD": "Europe",
    "MNP": "Oceania",
    "NOR": "Europe",
    "OMN": "Asia",
    "PAK": "Asia",
    "PLW": "Oceania",
    "PSE": "Asia",
    "PAN": "Other Americas",
    "PNG": "Oceania",
    "PRY": "Other Americas",
    "PER": "Other Americas",
    "PHL": "Asia",
    "PCN": "Oceania",
    "POL": "Europe",
    "PRT": "Europe",
    "PRI": "Other Americas",
    "QAT": "Asia",
    "REU": "Africa",
    "ROU": "Europe",
    "RUS": "Europe",
    "RWA": "Africa",
    "BLM": "Other Americas",
    "SHN": "Africa",
    "KNA": "Other Americas",
    "LCA": "Other Americas",
    "MAF": "Other Americas",
    "SPM": "Other Americas",
    "VCT": "Other Americas",
    "WSM": "Oceania",
    "SMR": "Europe",
    "STP": "Africa",
    "SAU": "Asia",
    "SEN": "Africa",
    "SRB": "Europe",
    "SYC": "Africa",
    "SLE": "Africa",
    "SGP": "Asia",
    "SXM": "Other Americas",
    "SVK": "Europe",
    "SVN": "Europe",
    "SLB": "Oceania",
    "SOM": "Africa",
    "ZAF": "Africa",
    "SGS": "Other Americas",
    "SSD": "Africa",
    "ESP": "Europe",
    "LKA": "Asia",
    "SDN": "Africa",
    "SUR": "Other Americas",
    "SJM": "Europe",
    "SWE": "Europe",
    "CHE": "Europe",
    "SYR": "Asia",
    "TWN": "",
    "TJK": "Asia",
    "TZA": "Africa",
    "THA": "Asia",
    "TLS": "Asia",
    "TGO": "Africa",
    "TKL": "Oceania",
    "TON": "Oceania",
    "TTO": "Other Americas",
    "TUN": "Africa",
    "TUR": "Asia",
    "TKM": "Asia",
    "TCA": "Other Americas",
    "TUV": "Oceania",
    "UGA": "Africa",
    "UKR": "Europe",
    "ARE": "Asia",
    "GBR": "Europe",
    "USA": "North America",
    "UMI": "Oceania",
    "URY": "Other Americas",
    "UZB": "Asia",
    "VUT": "Oceania",
    "VEN": "Other Americas",
    "VNM": "Asia",
    "VGB": "Other Americas",
    "VIR": "Other Americas",
    "WLF": "Oceania",
    "ESH": "Africa",
    "YEM": "Asia",
    "ZMB": "Africa",
    "ZWE": "Africa",
}


def get_willingness_to_pay(iso3):
    """
    Get the willingness to pay for a given ISO3 country code.

    Args:
        iso3 (str): The ISO3 country code.

    Returns:
        int: The willingness to pay for the region the country belongs to.
    """
    region = iso3_to_wp_region_dict.get(iso3, None)
    if region is not None:
        return willingness_to_pay_by_region.get(region, 0)
    return 0
