"""Tests for technology parameter default value changes.

These tests ensure that technology defaults are permissive (True) to respect Excel settings,
addressing the issue where form defaults were blocking technologies that Excel allowed.

NOTE: The form now uses dynamic technology fields extracted from DataPreparation,
so these tests verify the dynamic field generation rather than hardcoded fields.
"""

import pytest
from django.urls import reverse
from steeloweb.models import ModelRun


class TestTechnologyDefaults:
    """Test that technology defaults are permissive (True) to respect Excel."""

    @pytest.mark.django_db
    @pytest.mark.skip(reason="Form fields are now dynamically generated from DataPreparation")
    def test_esf_defaults_to_true(self):
        """ESF should default to True to respect Excel settings.

        NOTE: This test is skipped because technology fields are now dynamically
        generated from DataPreparation, not hardcoded in the form.
        """
        pass

    @pytest.mark.django_db
    @pytest.mark.skip(reason="Form fields are now dynamically generated from DataPreparation")
    def test_moe_defaults_to_true(self):
        """MOE should default to True to respect Excel settings.

        NOTE: This test is skipped because technology fields are now dynamically
        generated from DataPreparation, not hardcoded in the form.
        """
        pass

    @pytest.mark.django_db
    @pytest.mark.skip(reason="Form fields are now dynamically generated from DataPreparation")
    def test_dri_h2_defaults_to_true(self):
        """DRI-H2 should default to True to respect Excel settings.

        NOTE: This test is skipped because technology fields are now dynamically
        generated from DataPreparation, not hardcoded in the form.
        """
        pass

    @pytest.mark.django_db
    @pytest.mark.skip(reason="Form fields are now dynamically generated from DataPreparation")
    def test_other_technologies_remain_true(self):
        """Verify that other technologies still default to True.

        NOTE: This test is skipped because technology fields are now dynamically
        generated from DataPreparation, not hardcoded in the form.
        """
        pass

    @pytest.mark.django_db
    def test_form_submission_with_new_defaults_checked(
        self, mock_technology_extraction, client, valid_modelrun_form_data
    ):
        """When form submitted with technology settings, they should be saved correctly."""
        # Technology settings are now passed as dynamic fields
        clean_data = valid_modelrun_form_data.copy()
        # Add dynamic technology fields (these would be generated by HTMX in real usage)
        clean_data["tech_ESF_allowed"] = "true"
        clean_data["tech_MOE_allowed"] = "true"
        clean_data["tech_DRIH2EAF_allowed"] = "true"

        response = client.post(reverse("create-modelrun"), data=clean_data)
        assert response.status_code == 302, "Form submission should succeed"

        model_run = ModelRun.objects.latest("started_at")
        # Technology settings should be in the new format
        tech_settings = model_run.config.get("technology_settings", {})
        assert tech_settings.get("ESF", {}).get("allowed") is True, "ESF should be True in saved config"
        assert tech_settings.get("MOE", {}).get("allowed") is True, "MOE should be True in saved config"
        assert tech_settings.get("DRIH2EAF", {}).get("allowed") is True, "DRI-H2 should be True in saved config"

    @pytest.mark.django_db
    def test_explicit_false_still_works(self, mock_technology_extraction, client, valid_modelrun_form_data):
        """Explicitly setting technology to False should still disable it."""
        form_data = valid_modelrun_form_data.copy()
        # Dynamic technology fields - unchecked means not sent
        # We need to explicitly send "false" for disabled technologies
        form_data["tech_ESF_allowed"] = "false"
        form_data["tech_MOE_allowed"] = "false"
        form_data["tech_DRIH2EAF_allowed"] = "false"

        response = client.post(reverse("create-modelrun"), data=form_data)
        assert response.status_code == 302, "Form submission should succeed"

        model_run = ModelRun.objects.latest("started_at")

        # Should respect explicit False values in technology_settings
        tech_settings = model_run.config.get("technology_settings", {})
        assert tech_settings.get("ESF", {}).get("allowed") is False, "Should respect explicit False for ESF"
        assert tech_settings.get("MOE", {}).get("allowed") is False, "Should respect explicit False for MOE"
        assert tech_settings.get("DRIH2EAF", {}).get("allowed") is False, "Should respect explicit False for DRI-H2"
