"""SteelIQ Plotter - Class-based plotting system for Steel-IQ visualizations.

This module provides a centralized, class-based approach to creating plots with
consistent styling, footers, legends, and color schemes across all Steel-IQ visualizations.
"""

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import pandas as pd
import numpy as np
import logging
from matplotlib.figure import Figure
from matplotlib.ticker import MaxNLocator
from matplotlib.container import BarContainer
from pathlib import Path
from typing import Optional, TYPE_CHECKING
from dataclasses import dataclass, field
from datetime import datetime

if TYPE_CHECKING:
    from steelo.domain.models import PlotPaths
    from steelo.adapters.repositories.interface import PlantRepository

# Import global color schemes and constants
from steelo.utilities.plotting import tech2colours, region2colours
from steelo.domain.constants import T_TO_MT

logger = logging.getLogger(__name__)


# ============================================================================
# Configuration
# ============================================================================


@dataclass
class PlotConfig:
    """Configuration for consistent plot styling across all Steel-IQ visualizations.

    This class centralizes styling decisions for plots, making it easy to maintain
    consistency and customize appearance globally.

    Attributes:
        footer_template: Template string for plot footers. Use {date} and {version} placeholders.
        show_footer: Whether to display footer on plots
        legend_position: Legend position as (x, y) coordinates
        legend_loc: Legend location string (e.g., "upper left")
        legend_frameon: Whether to show frame around legend
        legend_fontsize: Font size for legend text
        default_dpi: Resolution for saved plots
        default_figsize_wide: Figure size for wide plots (width, height)
        default_figsize_square: Figure size for square plots (width, height)
        grid_alpha: Transparency of grid lines
        grid_linestyle: Style of grid lines
        tech_colors: Technology color mapping (will be copied from global tech2colours if not provided)
        region_colors: Region color mapping (will be copied from global region2colours if not provided)
    """

    footer_template: str = "Generated by Steel-IQ on {date}"
    show_footer: bool = True
    legend_position: tuple[float, float] = (1.05, 1)
    legend_loc: str = "upper left"
    legend_frameon: bool = True
    legend_fontsize: int = 10
    default_dpi: int = 300
    default_figsize_wide: tuple[int, int] = (12, 7)
    default_figsize_square: tuple[int, int] = (10, 10)
    grid_alpha: float = 0.3
    grid_linestyle: str = "--"
    tech_colors: dict[str, str] = field(default_factory=dict)
    region_colors: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        """Initialize color mappings from global defaults if not provided."""
        if not self.tech_colors:
            self.tech_colors = tech2colours.copy()
        if not self.region_colors:
            self.region_colors = region2colours.copy()


# ============================================================================
# Main Plotter Class
# ============================================================================


class SteelPlotter:
    """Main plotting class for Steel-IQ visualizations.

    This class provides a consistent interface for all Steel-IQ plots with
    centralized styling, footer management, and color scheme handling.

    Example:
        >>> config = PlotConfig(footer_template="Generated by Steel-IQ v2.0 on {date}")
        >>> plotter = SteelPlotter(config, plot_paths)
        >>> plotter.plot_capex_by_technology(data_collector.trace_capex)
        >>> plotter.plot_emissions_by_technology(data_collector.trace_emissions)
    """

    def __init__(self, config: Optional[PlotConfig] = None, plot_paths: Optional["PlotPaths"] = None):
        """Initialize the SteelIQ plotter.

        Args:
            config: Plot configuration. If None, uses default PlotConfig.
            plot_paths: Output paths for saving plots. Required for saving plots.
        """
        self.config = config or PlotConfig()
        self.plot_paths = plot_paths
        self.logger = logging.getLogger(f"{__name__}.SteelPlotter")

    # ========================================================================
    # Helper Methods
    # ========================================================================

    def _apply_footer(self, fig: Figure) -> None:
        """Apply consistent footer to a figure.

        Args:
            fig: Matplotlib figure to add footer to
        """
        if not self.config.show_footer:
            return

        footer_text = self.config.footer_template.format(
            date=datetime.now().strftime("%Y-%m-%d"),
            version="1.0",  # TODO: Get from package version
        )

        fig.text(
            0.99,
            0.01,
            footer_text,
            ha="right",
            va="bottom",
            fontsize=8,
            color="gray",
            style="italic",
        )

    def _style_legend(self, ax, title: str = "", handles=None, labels=None) -> None:
        """Apply consistent legend styling to an axes.

        Args:
            ax: Matplotlib axes to style legend for
            title: Legend title
            handles: Optional custom legend handles
            labels: Optional custom legend labels
        """
        if handles is not None and labels is not None:
            legend = ax.legend(
                handles=handles,
                labels=labels,
                title=title,
                bbox_to_anchor=self.config.legend_position,
                loc=self.config.legend_loc,
                frameon=self.config.legend_frameon,
                fontsize=self.config.legend_fontsize,
            )
        else:
            legend = ax.legend(
                title=title,
                bbox_to_anchor=self.config.legend_position,
                loc=self.config.legend_loc,
                frameon=self.config.legend_frameon,
                fontsize=self.config.legend_fontsize,
            )
        if legend and title:
            legend.get_title().set_fontweight("bold")

    def _save_figure(self, fig: Figure, filename: str, subdir: str = "pam_plots_dir") -> Path:
        """Save figure with consistent settings.

        Args:
            fig: Figure to save
            filename: Output filename
            subdir: Subdirectory attribute name from PlotPaths ("pam_plots_dir", "geo_plots_dir", etc.)

        Returns:
            Path where figure was saved

        Raises:
            ValueError: If plot_paths not set or subdirectory not found
        """
        if self.plot_paths is None:
            raise ValueError("plot_paths must be set to save figures")

        plot_dir = getattr(self.plot_paths, subdir, None)
        if plot_dir is None:
            raise ValueError(f"PlotPaths does not have attribute '{subdir}'")

        plot_dir.mkdir(parents=True, exist_ok=True)
        output_path = plot_dir / filename

        self._apply_footer(fig)
        fig.savefig(output_path, dpi=self.config.default_dpi, bbox_inches="tight")
        plt.close(fig)

        self.logger.info(f"Saved plot to {output_path}")
        return output_path

    def _ensure_tech_color(self, tech: str) -> str:
        """Get color for technology, assigning default if not found.

        Args:
            tech: Technology name

        Returns:
            Color code for the technology
        """
        if tech not in self.config.tech_colors:
            self.config.tech_colors[tech] = "brown"
            self.logger.warning(f"No color defined for technology '{tech}', using brown")
        return self.config.tech_colors[tech]

    # ========================================================================
    # Plotting Methods
    # ========================================================================

    def plot_capex_by_technology(
        self,
        trace_capex: dict[int, dict[str, dict[str, float]]],
        iso3_filter: Optional[str] = None,
    ) -> Optional[Path]:
        """Plot total CAPEX investments by technology over years as a stacked bar chart.

        Args:
            trace_capex: Nested dict {year: {technology: {iso3: total_capex_usd}}}
            iso3_filter: Optional ISO3 country code to filter investments

        Returns:
            Path to saved plot, or None if no data to plot
        """
        if not trace_capex:
            self.logger.warning("No CAPEX data to plot")
            return None

        # Get full year range
        all_years = sorted(trace_capex.keys())
        if not all_years:
            return None

        year_min = min(all_years)
        year_max = max(all_years)
        full_year_range = list(range(year_min, year_max + 1))

        # Convert to DataFrame
        data_rows = []
        for year, techs in trace_capex.items():
            for tech, locations in techs.items():
                for iso3, capex in locations.items():
                    if iso3_filter is None or iso3 == iso3_filter:
                        data_rows.append({"year": year, "technology": tech, "iso3": iso3, "capex": capex})

        if not data_rows:
            self.logger.warning(f"No CAPEX data after filtering{f' for {iso3_filter}' if iso3_filter else ''}")
            return None

        df = pd.DataFrame(data_rows)
        df["capex_bn"] = df["capex"] / 1e9

        # Aggregate by year and technology
        capex_by_year_tech = df.groupby(["year", "technology"])["capex_bn"].sum().unstack("technology", fill_value=0)
        capex_by_year_tech = capex_by_year_tech.reindex(full_year_range, fill_value=0)

        # Ensure colors for all technologies
        for tech in capex_by_year_tech.columns:
            self._ensure_tech_color(tech)

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        capex_by_year_tech.plot.bar(
            stacked=True,
            ax=ax,
            color=[self.config.tech_colors.get(tech, "brown") for tech in capex_by_year_tech.columns],
            width=0.8,
        )

        # Formatting
        location_str = f" in {iso3_filter}" if iso3_filter else " (Global)"
        ax.set_title(f"CAPEX Investments by Technology{location_str}", fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Total CAPEX (Billion USD)", fontsize=12)
        self._style_legend(ax, title="Technology")
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # X-axis formatting
        ax.set_xticks(range(len(full_year_range)))
        ax.set_xticklabels([str(year) for year in full_year_range], rotation=45, ha="right")

        # Thin out labels if too many years
        if len(full_year_range) > 20:
            step = 5 if len(full_year_range) > 50 else 2
            for i, label in enumerate(ax.xaxis.get_ticklabels()):
                if i % step != 0:
                    label.set_visible(False)

        # Add value labels on significant bars
        for container in ax.containers:
            if isinstance(container, BarContainer):
                heights = [patch.get_height() for patch in container.patches]
                labels = [f"${float(h):.1f}B" if float(h) > 0.1 else "" for h in heights]
                ax.bar_label(container, labels=labels, label_type="center", fontsize=8, color="white", weight="bold")

        fig.tight_layout()

        # Save
        filename = f"capex_by_technology_and_year{'_' + iso3_filter if iso3_filter else ''}.png"
        return self._save_figure(fig, filename)

    def plot_emissions_by_technology(
        self,
        trace_emissions: dict[int, dict[str, float]],
    ) -> Optional[Path]:
        """Plot emissions by technology over time as a stacked area chart.

        Args:
            trace_emissions: Nested dict {year: {technology: total_emissions_tCO2e}}

        Returns:
            Path to saved plot, or None if no data to plot
        """
        if not trace_emissions:
            self.logger.warning("No emissions data to plot")
            return None

        # Convert to DataFrame
        data_rows = []
        for year, techs in trace_emissions.items():
            for tech, emissions in techs.items():
                data_rows.append({"year": year, "technology": tech, "emissions": emissions})

        if not data_rows:
            return None

        df = pd.DataFrame(data_rows)
        df["emissions_mt"] = df["emissions"] / 1e6

        # Pivot to get technologies as columns
        df_pivot = df.pivot(index="year", columns="technology", values="emissions_mt")
        df_pivot = df_pivot.fillna(0)

        # Ensure colors for all technologies
        for tech in df_pivot.columns:
            self._ensure_tech_color(tech)

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        df_pivot.plot.area(
            ax=ax,
            color=[self.config.tech_colors.get(tech, "brown") for tech in df_pivot.columns],
            alpha=0.8,
            linewidth=2,
        )

        # Formatting
        ax.set_title("Emissions by Technology Over Time", fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Total Emissions (Mt CO2e)", fontsize=12)
        self._style_legend(ax, title="Technology")
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # X-axis formatting
        years = sorted(df_pivot.index)
        ax.set_xlim(years[0], years[-1])
        ax.xaxis.set_major_locator(MaxNLocator(integer=True, nbins=min(len(years), 20)))

        fig.tight_layout()

        return self._save_figure(fig, "emissions_by_technology_over_time.png")

    def plot_iron_ore_by_quality(
        self,
        trace_iron_ore: dict[int, dict[str, float]],
    ) -> Optional[Path]:
        """Plot iron ore consumption by quality over time as a stacked area chart.

        Args:
            trace_iron_ore: Nested dict {year: {quality: total_consumption_tonnes}}

        Returns:
            Path to saved plot, or None if no data to plot
        """
        if not trace_iron_ore:
            self.logger.warning("No iron ore data to plot")
            return None

        # Convert to DataFrame
        data_rows = []
        for year, qualities in trace_iron_ore.items():
            for quality, consumption in qualities.items():
                data_rows.append({"year": year, "quality": quality, "consumption": consumption})

        if not data_rows:
            return None

        df = pd.DataFrame(data_rows)
        df["consumption_mt"] = df["consumption"] / 1e6

        # Pivot
        df_pivot = df.pivot(index="year", columns="quality", values="consumption_mt")
        df_pivot = df_pivot.fillna(0)

        # Define colors for iron ore qualities
        quality_colors = {
            "io_high": "#2E7D32",  # green (highest quality)
            "io_mid": "#1976D2",  # blue (mid quality)
            "io_low": "#D32F2F",  # red (lowest quality)
        }

        # Assign colors
        colors_for_plot = []
        for quality in df_pivot.columns:
            quality_lower = quality.lower()
            color_found = False
            for key, color in quality_colors.items():
                if key in quality_lower:
                    colors_for_plot.append(color)
                    color_found = True
                    break
            if not color_found:
                colors_for_plot.append("brown")
                self.logger.warning(f"No color defined for iron ore quality '{quality}', using brown")

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        df_pivot.plot.area(
            ax=ax,
            color=colors_for_plot,
            alpha=0.8,
            linewidth=2,
        )

        # Formatting
        ax.set_title("Iron Ore Consumption by Quality Over Time", fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Total Consumption (Mt)", fontsize=12)
        self._style_legend(ax, title="Quality")
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # X-axis formatting
        years = sorted(df_pivot.index)
        ax.set_xlim(years[0], years[-1])
        ax.xaxis.set_major_locator(MaxNLocator(integer=True, nbins=min(len(years), 20)))

        fig.tight_layout()

        return self._save_figure(fig, "iron_ore_by_quality_over_time.png")

    def plot_metallic_charges(
        self,
        trace_metallic_charges: dict[int, dict[str, float]],
    ) -> Optional[Path]:
        """Plot metallic charge consumption over time as a stacked area chart.

        Args:
            trace_metallic_charges: Nested dict {year: {charge_type: total_consumption_tonnes}}

        Returns:
            Path to saved plot, or None if no data to plot
        """
        if not trace_metallic_charges:
            self.logger.warning("No metallic charge data to plot")
            return None

        # Convert to DataFrame
        data_rows = []
        for year, charges in trace_metallic_charges.items():
            for charge_type, consumption in charges.items():
                data_rows.append({"year": year, "charge_type": charge_type, "consumption": consumption})

        if not data_rows:
            return None

        df = pd.DataFrame(data_rows)
        df["consumption_mt"] = df["consumption"] / 1e6

        # Pivot
        df_pivot = df.pivot(index="year", columns="charge_type", values="consumption_mt")
        df_pivot = df_pivot.fillna(0)

        # Use colormap for automatic color assignment
        n_charges = len(df_pivot.columns)
        if n_charges <= 10:
            cmap = cm.get_cmap("tab10")
        elif n_charges <= 20:
            cmap = cm.get_cmap("tab20")
        else:
            cmap = cm.get_cmap("hsv")

        colors_for_plot = [cmap(i / n_charges) for i in range(n_charges)]

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        df_pivot.plot.area(
            ax=ax,
            color=colors_for_plot,
            alpha=0.8,
            linewidth=2,
        )

        # Formatting
        ax.set_title("Metallic Charge Consumption Over Time", fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Total Consumption (Mt)", fontsize=12)
        self._style_legend(ax, title="Charge Type")
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # X-axis formatting
        years = sorted(df_pivot.index)
        ax.set_xlim(years[0], years[-1])
        ax.xaxis.set_major_locator(MaxNLocator(integer=True, nbins=min(len(years), 20)))

        fig.tight_layout()

        return self._save_figure(fig, "metallic_charges_over_time.png")

    def plot_steel_cost_curve(
        self,
        curve: list[dict[str, float]],
        demand: float,
        filename: str = "steel_cost_curve.png",
    ) -> Optional[Path]:
        """Plot a steel cost curve with marginal producer highlighted.

        Plots a steel cost curve (sorted by ascending cost) and indicates the
        marginal producer for a given demand level.

        Args:
            curve: List of dicts with 'cumulative_capacity' and 'production_cost'
            demand: Demanded capacity (will highlight intersection point)
            filename: Output filename for the plot

        Returns:
            Path to saved plot, or None if no data
        """
        if not curve:
            self.logger.warning("No cost curve data to plot")
            return None

        # Extract x (cumulative capacities) and y (production costs) from the curve
        cumulative_capacities = [point["cumulative_capacity"] for point in curve]
        production_costs = [point["production_cost"] for point in curve]

        # Convert capacities from t to kt
        cumulative_capacities = [x / 1000 for x in cumulative_capacities]
        demand_kt = demand / 1000

        # Find maximum capacity to check demand boundaries
        max_capacity = cumulative_capacities[-1] if curve else 0

        # If demand is out of range, clip or note it
        if demand_kt < 0:
            demand_kt = 0
        elif demand_kt > max_capacity:
            self.logger.warning(
                f"Demand ({demand_kt}) exceeds total available capacity ({max_capacity}). "
                "Marginal producer cost will be that of the final producer."
            )
            demand_kt = max_capacity

        # Find the marginal producer
        marginal_producer = None
        for point in curve:
            if point["cumulative_capacity"] / 1000 >= demand_kt:
                marginal_producer = point
                break

        # Create plot
        fig, ax = plt.subplots(figsize=(10, 6))

        # Plot cost curve as step plot
        ax.step(cumulative_capacities, production_costs, where="post", label="Cost Curve", linewidth=2)

        # Plot vertical line at demand level
        ax.axvline(x=demand_kt, color="red", linestyle="--", label="Demand", linewidth=1.5)

        # If we found a valid marginal producer, annotate it
        if marginal_producer:
            marginal_x = demand_kt
            marginal_cost = marginal_producer["production_cost"]

            # Horizontal line at the marginal cost
            ax.axhline(y=marginal_cost, color="gray", linestyle="--", linewidth=1)

            # Mark the intersection
            ax.scatter(marginal_x, marginal_cost, color="red", zorder=5, s=100)

            # Add text annotation
            ax.text(
                marginal_x,
                marginal_cost,
                f"  Marginal producer cost = ${marginal_cost:.2f}/t",
                color="red",
                verticalalignment="bottom",
                fontsize=10,
            )

        # Styling
        ax.set_title("Steel Cost Curve", fontsize=14, fontweight="bold")
        ax.set_xlabel("Cumulative Capacity (kt)", fontsize=12)
        ax.set_ylabel("Production Cost (US$/t)", fontsize=12)
        self._style_legend(ax)
        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        fig.tight_layout()

        return self._save_figure(fig, filename)

    def plot_cost_curve_per_region(
        self,
        plants: "PlantRepository",
        filename: str = "cost_curve_per_region.png",
    ) -> Optional[Path]:
        """Plot cost curve with regions colored separately.

        Args:
            plants: PlantRepository containing plant data
            filename: Output filename for the plot

        Returns:
            Path to saved plot, or None if no data
        """
        # Initialize variables for plotting
        current_capacity = 0
        regional_data: dict = {}

        # Collect data for rectangle plotting
        for plant in plants.list():
            if not hasattr(plant, "average_steel_cost") or not hasattr(plant, "steel_capacity"):
                continue
            region = plant.location.region
            regional_data[region] = regional_data.get(region, []) + [
                (
                    (float(plant.steel_capacity) if plant.steel_capacity is not None else 0.0)
                    * (float(plant.average_steel_cost) if plant.average_steel_cost is not None else 0.0),
                    float(plant.steel_capacity) if plant.steel_capacity is not None else 0.0,
                )
            ]

        if not regional_data:
            self.logger.warning("No plant data to plot cost curve per region")
            return None

        # Prepare sorted rectangles
        sorted_rectangles = []
        region_colors = {}

        # Use configured region colors if available, otherwise generate colors
        if self.config.region_colors:
            region_colors = self.config.region_colors.copy()

        # Generate colors for regions not in config
        color_palette = plt.cm.get_cmap("tab20", len(regional_data))
        for idx, region in enumerate(regional_data.keys()):
            if region not in region_colors:
                region_colors[region] = color_palette(idx)

        current_capacity = 0
        for region, data in regional_data.items():
            total_cost = sum([x[0] for x in data])
            total_capacity = sum([x[1] for x in data])
            if total_capacity > 0:
                width = total_capacity * T_TO_MT  # Convert to megatons
                height = total_cost / total_capacity
                sorted_rectangles.append((current_capacity, height, width, region))
                current_capacity += width

        # Sort rectangles by height (average cost) in ascending order
        sorted_rectangles.sort(key=lambda x: x[1])

        # Reset current capacity for sorted rectangles
        current_capacity = 0
        final_rectangles = []
        for x_start, height, width, region in sorted_rectangles:
            final_rectangles.append((current_capacity, height, width, region))
            current_capacity += width

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        for x_start, height, width, region in final_rectangles:
            ax.bar(
                x_start,
                height,
                width=width,
                align="edge",
                edgecolor="black",
                color=region_colors[region],
                label=region,
            )

        # Add legend (remove duplicates)
        handles, labels = ax.get_legend_handles_labels()
        by_label = dict(zip(labels, handles))
        self._style_legend(ax, title="Region", handles=list(by_label.values()), labels=list(by_label.keys()))

        # Styling
        ax.set_xlabel("Cumulative Annual Capacity (Mt/year)", fontsize=12)
        ax.set_ylabel("Cost per Unit (US$/t)", fontsize=12)
        ax.set_title("Cost Curve per Region", fontsize=14, fontweight="bold")
        ax.grid(True, linestyle="--", alpha=self.config.grid_alpha)

        fig.tight_layout()

        return self._save_figure(fig, filename)

    def plot_cost_curve_for_commodity(
        self,
        cost_curve: list[dict],
        total_demand: float,
        filename: str = "cost_curve.png",
    ) -> Optional[Path]:
        """Plot cost curve for a commodity with demand line.

        Args:
            cost_curve: List of dicts with 'cumulative_capacity' and 'production_cost'
            total_demand: Total demand to highlight on the curve
            filename: Output filename for the plot

        Returns:
            Path to saved plot, or None if no data
        """
        if not cost_curve:
            self.logger.warning("No cost curve data to plot for commodity")
            return None

        # Prepare x and y data for plotting
        x_vals = []
        y_vals = []

        for point in cost_curve:
            # Handle cumulative_capacity that may be a Volumes object
            try:
                cap = float(point["cumulative_capacity"])
            except (TypeError, ValueError):
                cap = (
                    point["cumulative_capacity"].value
                    if hasattr(point["cumulative_capacity"], "value")
                    else point["cumulative_capacity"]
                )

            x_vals.append(cap)
            y_vals.append(point["production_cost"])

        # Create the plot
        fig, ax = plt.subplots(figsize=(10, 6))
        ax.step(x_vals, y_vals, where="post", label="Cost Curve", linewidth=2)

        # Add demand line
        ax.axvline(x=total_demand, color="red", linestyle="--", label="Total Demand", linewidth=1.5)

        # Styling
        ax.set_xlabel("Cumulative Capacity", fontsize=12)
        ax.set_ylabel("Production Cost", fontsize=12)
        ax.set_title("Cost Curve", fontsize=14, fontweight="bold")
        self._style_legend(ax)
        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        fig.tight_layout()

        return self._save_figure(fig, filename)

    def plot_cost_curve_with_breakdown(
        self,
        data_file: pd.DataFrame,
        product_type: str,
        year: int,
        show_breakdown: bool = True,
        filename: Optional[str] = None,
    ) -> Optional[Path]:
        """Plot cost curve with stacked bar breakdown showing cost components per furnace group.

        Args:
            data_file: DataFrame with furnace group data
            product_type: Type of product ('steel' or 'iron')
            year: Year to plot
            show_breakdown: If True, show cost breakdown as stacked bars
            filename: Optional custom filename (default: auto-generated from product/year)

        Returns:
            Path to saved plot, or None if no data
        """
        df = data_file.groupby(["furnace_group_id", "year"], as_index=False).first().set_index(["product", "year"])

        # Check if the requested year exists in the data
        available_years = df.index.get_level_values("year").unique()
        if year not in available_years:
            self.logger.warning(f"Year {year} not found in data. Available years: {sorted(available_years)}")
            # Use the closest available year
            year = max([y for y in available_years if y <= year] or [min(available_years)])
            self.logger.info(f"Using year {year} instead for cost curve plot")

        # Check if product_type exists
        if product_type not in df.index.get_level_values("product"):
            self.logger.warning(f"Product type '{product_type}' not found in data. Skipping cost curve plot.")
            return None

        # Sort the index to avoid performance warning
        df = df.sort_index()

        # Get the data for the specific product and year
        demand = df.loc[product_type].loc[year].production.sum()

        # Prepare cost breakdown components
        component_columns = []

        if show_breakdown:
            # Extract cost components from the data
            self.logger.debug(f"Available columns in df: {list(df.columns)}")
            if "cost_breakdown" in df.columns:
                # If we have the cost_breakdown dictionary column (nested by feedstock)
                cost_df = df.loc[(product_type, year)].copy()

                # Parse and flatten the cost_breakdown structure
                for idx, row in cost_df.iterrows():
                    if pd.notna(row.get("cost_breakdown")) and isinstance(row["cost_breakdown"], dict):
                        # Aggregate costs across all feedstocks
                        aggregated_costs = {}

                        for feedstock, costs in row["cost_breakdown"].items():
                            if isinstance(costs, dict):
                                for cost_type, value in costs.items():
                                    if cost_type == "total_cost":
                                        if "material_cost" not in aggregated_costs:
                                            aggregated_costs["material_cost"] = 0
                                        aggregated_costs["material_cost"] += value
                                    elif cost_type not in ["demand", "unit_cost"]:
                                        if cost_type not in aggregated_costs:
                                            aggregated_costs[cost_type] = 0
                                        aggregated_costs[cost_type] += value

                        # Add the aggregated costs as columns to the dataframe
                        for cost_type, value in aggregated_costs.items():
                            cost_df.at[idx, cost_type] = value

                # Now identify component columns from the flattened data
                if "material_cost" in cost_df.columns:
                    component_columns.append("material_cost")

                # Handle columns with spaces in names
                for col in ["fixed opex", "carbon cost", "debt share"]:
                    if col in cost_df.columns:
                        new_col = col.replace(" ", "_")
                        cost_df[new_col] = cost_df[col]
                        component_columns.append(new_col)

                # Energy columns
                energy_cols = [
                    col
                    for col in cost_df.columns
                    if col in ["electricity", "coal", "natural gas", "natural_gas", "bf gas", "bof gas", "cog", "steam"]
                ]
                for col in energy_cols:
                    if pd.api.types.is_numeric_dtype(cost_df[col]):
                        component_columns.append(col)
            else:
                # Build cost breakdown from available columns
                cost_df = df.loc[(product_type, year)].copy()

                # Add cost breakdown columns that start with "cost_breakdown - "
                breakdown_cols = [col for col in cost_df.columns if col.startswith("cost_breakdown - ")]
                breakdown_names = set()

                for col in breakdown_cols:
                    clean_name = col.replace("cost_breakdown - ", "").strip()
                    cost_df[clean_name] = cost_df[col]
                    component_columns.append(clean_name)
                    breakdown_names.add(clean_name)

                # Material costs - only add if not already covered by cost breakdown
                if "material_cost" not in breakdown_names:
                    if "material_unit_cost" in cost_df.columns:
                        cost_df["material_cost"] = cost_df["material_unit_cost"]
                        component_columns.append("material_cost")
                    elif "material_cost" in cost_df.columns:
                        component_columns.append("material_cost")
                    elif "material cost" in cost_df.columns:
                        cost_df["material_cost"] = cost_df["material cost"]
                        component_columns.append("material_cost")

                # Fixed OPEX - only add if not already covered by cost breakdown
                if "unit_fopex" in cost_df.columns and "unit fopex" not in breakdown_names:
                    component_columns.append("unit_fopex")

                # Carbon cost - only add if not already covered by cost breakdown
                if "carbon_cost" in cost_df.columns and "carbon cost" not in breakdown_names:
                    component_columns.append("carbon_cost")
                elif "carbon_cost_per_unit" in cost_df.columns and "carbon cost" not in breakdown_names:
                    if "production" in cost_df.columns:
                        cost_df["carbon_cost"] = cost_df["carbon_cost_per_unit"] * cost_df["production"]
                        component_columns.append("carbon_cost")

                # Debt service - only add if not already covered by cost breakdown
                if "debt_share" in cost_df.columns and "debt share" not in breakdown_names:
                    component_columns.append("debt_share")

                # Calculate total production cost as sum of components
                if component_columns:
                    cost_df["production_cost"] = cost_df[component_columns].sum(axis=1, skipna=True)
                else:
                    cost_df["production_cost"] = df["unit_production_cost"]
        else:
            # Original simple calculation
            df["production_cost"] = df["unit_production_cost"]
            cost_df = df.loc[(product_type, year)][["production_cost", "region", "capacity"]].copy()

        # Sort by production cost
        cost_df = cost_df.sort_values("production_cost")

        # Check if we have valid data
        if cost_df.empty:
            self.logger.warning(f"No data for {product_type} in year {year}. Skipping cost curve plot.")
            return None

        if cost_df["production_cost"].isna().all():
            self.logger.warning(f"All production costs are NaN for {product_type} in year {year}.")
            return None

        # Remove rows with NaN production costs
        cost_df = cost_df.dropna(subset=["production_cost"])
        if cost_df.empty:
            self.logger.warning(f"No valid production costs for {product_type} in year {year}.")
            return None

        cost_df["clearing_capacity"] = cost_df["capacity"].cumsum()

        # Create the plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)
        cum_x = 0.0

        if show_breakdown and component_columns:
            # Define colors for each cost component
            component_colors = {
                "material_cost": "#8B4513",  # Saddle brown
                "electricity": "#FFD700",  # Gold
                "coal": "#2F4F4F",  # Dark slate gray
                "natural_gas": "#87CEEB",  # Sky blue
                "bf gas": "#4682B4",  # Steel blue
                "bof gas": "#5F9EA0",  # Cadet blue
                "cog": "#696969",  # Dim gray
                "steam": "#FFA500",  # Orange
                "unit_fopex": "#708090",  # Slate gray
                "unit fopex": "#708090",  # Slate gray (space version)
                "carbon_cost": "#DC143C",  # Crimson
                "carbon cost": "#DC143C",  # Crimson (space version)
                "debt_share": "#4B0082",  # Indigo
                "debt share": "#4B0082",  # Indigo (space version)
            }

            # Plot stacked bars for each furnace group
            for _, row in cost_df.iterrows():
                cap = row["capacity"]
                x0 = cum_x
                x1 = cum_x + cap

                # Stack the cost components
                y_bottom = 0
                for component in component_columns:
                    if component in row and pd.notna(row[component]) and row[component] > 0:
                        component_value = row[component]

                        # Get color for this component
                        if component in component_colors:
                            color = component_colors[component]
                        else:
                            color = cm.Set3(hash(component) % 12 / 12)
                            component_colors[component] = color

                        # Draw the stacked segment
                        ax.fill_between(
                            [x0, x1],
                            [y_bottom, y_bottom],
                            [y_bottom + component_value, y_bottom + component_value],
                            color=color,
                            alpha=0.8,
                            linewidth=0.5,
                            edgecolor="black",
                            label=component if cum_x == 0 else "",  # Only label once
                        )

                        y_bottom += component_value

                # Add region border/outline
                rectangle = plt.Rectangle(
                    (x0, 0),
                    cap,
                    row["production_cost"],
                    fill=False,
                    edgecolor="black",
                    linewidth=2,
                    linestyle="-",
                )
                ax.add_patch(rectangle)

                cum_x = x1
        else:
            # Original simple filled rectangles (fallback)
            for _, row in cost_df.iterrows():
                cost = row["production_cost"]
                cap = row["capacity"]
                color = "steelblue"

                x0 = cum_x
                x1 = cum_x + cap

                ax.fill_between([x0, x1], [cost, cost], [0, 0], color=color, step="pre", linewidth=0)
                ax.hlines(y=cost, xmin=x0, xmax=x1, colors="black", linewidth=0.8, zorder=2)

                cum_x = x1

        # Add market clearing price and demand lines
        clearing_cost = (
            cost_df[cost_df["clearing_capacity"] <= demand].iloc[-1].production_cost if not cost_df.empty else 0
        )

        ax.axhline(y=clearing_cost, color="r", linestyle="--", linewidth=1.5, label="Market clearing price")
        ax.axvline(x=demand, color="r", linestyle="--", linewidth=1.5, label="Demand")

        # Add clearing price annotation
        ax.text(
            x=cost_df.iloc[-1]["clearing_capacity"] * 0.7 if not cost_df.empty else 0,
            y=clearing_cost + 30,
            s=f"Market clearing price = {clearing_cost:.1f} $/t",
            ha="center",
            va="bottom",
            color="black",
            fontsize=10,
            backgroundcolor="white",
            alpha=0.8,
        )

        # Set title and labels
        breakdown_text = " with Cost Breakdown" if show_breakdown else ""
        ax.set_title(
            f"Cost Curve for {product_type.capitalize()} in {year}{breakdown_text}",
            fontsize=14,
            fontweight="bold",
        )
        ax.set_xlabel("Cumulative Capacity (kt)", fontsize=12)
        ax.set_ylabel("Production Cost ($/t)", fontsize=12)

        # Set axis limits
        if cum_x > 0:
            ax.set_xlim(0, cum_x * 1.02)
        else:
            ax.set_xlim(0, 1)

        max_cost = cost_df["production_cost"].max()
        if pd.isna(max_cost) or np.isinf(max_cost) or max_cost <= 0:
            self.logger.warning(f"Invalid max production cost: {max_cost}. Using default y-axis range.")
            ax.set_ylim(0, 1000)
        else:
            ax.set_ylim(0, max_cost * 1.1)

        # Create legend
        if show_breakdown and component_columns:
            handles, labels = ax.get_legend_handles_labels()
            if handles:
                ax.legend(
                    handles=handles[: len(component_columns)],
                    title="Cost Components",
                    loc="upper left",
                    frameon=True,
                    fontsize=9,
                )

        # Add grid
        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        fig.tight_layout()

        # Generate filename if not provided
        if filename is None:
            filename = (
                f"{product_type}_cost_curve_breakdown_{year}.png"
                if show_breakdown
                else f"{product_type}_cost_curve_{year}.png"
            )

        return self._save_figure(fig, filename)

    def plot_capacity_development_by_technology(
        self,
        data_file: pd.DataFrame,
        units: str = "Mt",
        filename: str = "Capacity_development_by_technology.png",
    ) -> Optional[Path]:
        """Plot year-on-year capacity development by technology.

        Shows the change in capacity for each technology from year to year as a grouped bar chart.

        Args:
            data_file: DataFrame with columns: furnace_group_id, year, technology, capacity, product
            units: Unit string for y-axis label (e.g., "Mt", "ktpa")
            filename: Output filename for the plot

        Returns:
            Path to saved plot, or None if no data

        Raises:
            ValueError: If required columns are missing from data_file
        """
        # Validate required columns
        required_cols = ["furnace_group_id", "year", "technology", "capacity", "product"]
        missing_cols = [col for col in required_cols if col not in data_file.columns]
        if missing_cols:
            raise ValueError(f"DataFrame missing required columns: {missing_cols}")

        data_file = data_file.copy()

        # Get unique technologies and ensure all have colors
        unique_techs = data_file["technology"].unique()
        tech_colors = {}
        for tech in unique_techs:
            tech_colors[tech] = self._ensure_tech_color(tech)

        # Calculate year-on-year development by technology
        by_technology = (
            data_file.drop_duplicates(subset=["furnace_group_id", "year"])
            .groupby(["year", "technology"])["capacity"]
            .sum()
            .unstack("technology")
        )

        # Fill missing values with 0 to ensure all technologies appear in diff
        by_technology = by_technology.fillna(0)

        # Calculate year-on-year difference
        capacity_diff = by_technology.diff()

        # Create the plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        capacity_diff.plot(
            ax=ax,
            kind="bar",
            stacked=False,
            ylabel=f"Capacity [{units}]",
            xlabel="Year",
            legend=True,
            color=tech_colors,
        )

        # Styling
        ax.set_title("Year-on-Year Capacity Development by Technology", fontsize=14, fontweight="bold")
        self._style_legend(ax, title="Technology")
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # Rotate x-axis labels for better readability
        ax.tick_params(axis="x", rotation=45)

        fig.tight_layout()

        return self._save_figure(fig, filename)

    def plot_area_chart_by_region_or_technology(
        self,
        dataframe: pd.DataFrame,
        column_name: str,
        title: str,
        units: str,
        pivot_columns: list[str],
        product_type: str = "steel",
        filename: Optional[str] = None,
    ) -> Optional[Path]:
        """Plot a stacked area chart of a column grouped by region or technology.

        This is a general-purpose method for creating stacked area charts showing
        how capacity, production, or other metrics change over time, broken down
        by region or technology.

        Args:
            dataframe: DataFrame with columns: furnace_group_id, year, product, region/technology
            column_name: Column to plot (e.g., "capacity", "production")
            title: Plot title
            units: Unit string for y-axis label (e.g., "Mtpa", "ktpa")
            pivot_columns: List of columns to pivot by (e.g., ["region"] or ["technology"])
            product_type: Filter by product type ("steel" or "iron")
            filename: Optional custom filename (auto-generated if None)

        Returns:
            Path to saved plot, or None if no data

        Raises:
            ValueError: If required columns are missing
        """
        # Validate required columns
        required_cols = ["furnace_group_id", "year", "product", column_name]
        missing_cols = [col for col in required_cols if col not in dataframe.columns]
        if missing_cols:
            raise ValueError(f"DataFrame missing required columns: {missing_cols}")

        # Check pivot columns exist
        for col in pivot_columns:
            if col not in dataframe.columns:
                raise ValueError(f"Pivot column '{col}' not found in DataFrame")

        dataframe = dataframe.copy()

        # Filter by product type and remove duplicates
        dataframe = dataframe.drop_duplicates(subset=["furnace_group_id", "year"])
        dataframe = dataframe[dataframe["product"] == product_type]

        if dataframe.empty:
            self.logger.warning(f"No data for product type '{product_type}' to plot")
            return None

        # Pivot to get a column for each region/technology
        df_pivot = dataframe.pivot_table(index="year", columns=pivot_columns, values=column_name, aggfunc="sum").fillna(
            0
        )

        if df_pivot.empty:
            self.logger.warning(f"No data after pivoting by {pivot_columns}")
            return None

        # Determine color map based on pivot columns
        # Only include colors for labels that actually exist in the data
        if pivot_columns == ["region"]:
            base_colours = self.config.region_colors if self.config.region_colors else region2colours
            legend_title = "Region"
        elif pivot_columns == ["technology"]:
            base_colours = self.config.tech_colors if self.config.tech_colors else tech2colours
            legend_title = "Technology"
        else:
            base_colours = {}
            legend_title = "_".join(pivot_columns)

        # Build color map for all columns that exist in the pivoted data
        # Pandas requires ALL columns to have colors if a color dict is provided
        colour_map = {}
        colormap = cm.get_cmap("tab10")  # Default colormap for auto-assignment

        for idx, col in enumerate(df_pivot.columns):
            if col in base_colours:
                colour_map[col] = base_colours[col]
            elif pivot_columns == ["technology"]:
                # Use _ensure_tech_color for technologies not in the base map
                colour_map[col] = self._ensure_tech_color(col)
            else:
                # Auto-assign color for regions/other columns not in the base map
                colour_map[col] = colormap(idx % 10)

        # Create the plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        df_pivot.plot(
            ax=ax,
            kind="area",
            stacked=True,
            color=colour_map,
        )

        # Styling
        ax.set_title(title, fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel(f"{column_name.replace('_', ' ').title()} [{units}]", fontsize=12)

        # Fix region/technology colors if needed (pandas sometimes doesn't apply them correctly)
        if pivot_columns == ["region"] or pivot_columns == ["technology"]:
            handles, labels = ax.get_legend_handles_labels()
            for handle, label in zip(handles, labels):
                if label in colour_map:
                    if hasattr(handle, "set_facecolor"):
                        handle.set_facecolor(colour_map[label])

        self._style_legend(ax, title=legend_title)

        # Set x-axis to show only integer years
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        if not df_pivot.index.empty:
            ax.set_xlim(df_pivot.index.min(), df_pivot.index.max())

        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        fig.tight_layout()

        # Generate filename if not provided
        if filename is None:
            pivot_str = pivot_columns[0] if pivot_columns else "unknown"
            filename = f"{product_type}_{column_name}_development_by_{pivot_str}.png"

        return self._save_figure(fig, filename)
