# Generated by Django 5.1.7 on 2025-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the model run was started"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, help_text="When the model run finished", null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        help_text="Current state of the model run",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration parameters for the model run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Run",
                "verbose_name_plural": "Model Runs",
                "ordering": ["-started_at"],
            },
        ),
    ]
