# Generated by Django 5.1.7 on 2025-04-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0002_modelrun_error_message_modelrun_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of the repository", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Description of the repository")),
                (
                    "repo_type",
                    models.CharField(
                        choices=[("plants", "Plants"), ("demand_centers", "Demand Centers")],
                        default="plants",
                        help_text="Type of repository",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(help_text="Repository JSON file", upload_to="repositories/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the repository was created")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the repository was last updated")),
            ],
            options={
                "verbose_name": "Repository",
                "verbose_name_plural": "Repositories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="modelrun",
            name="plants_repository",
            field=models.ForeignKey(
                blank=True,
                help_text="Custom plants repository to use for this run",
                limit_choices_to={"repo_type": "plants"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_runs",
                to="steeloweb.repository",
            ),
        ),
    ]
