# Generated by Django 5.2 on 2025-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0003_repository_modelrun_plants_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="progress",
            field=models.JSONField(blank=True, default=dict, help_text="Progress from the model run"),
        ),
    ]
