# Generated by Django 5.2 on 2025-05-09 16:29

import django.db.models.deletion
import steeloweb.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0004_modelrun_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lcoe_map",
                    models.ImageField(
                        upload_to=steeloweb.models.result_image_upload_path,
                        verbose_name="LCOE Map",
                    ),
                ),
                (
                    "lcoh_map",
                    models.ImageField(
                        upload_to=steeloweb.models.result_image_upload_path,
                        verbose_name="LCOH Map",
                    ),
                ),
                (
                    "priority_locations_iron",
                    models.ImageField(
                        upload_to=steeloweb.models.result_image_upload_path,
                        verbose_name="Priority Locations for Iron",
                    ),
                ),
                (
                    "priority_locations_steel",
                    models.ImageField(
                        upload_to=steeloweb.models.result_image_upload_path,
                        verbose_name="Priority Locations for Steel",
                    ),
                ),
                (
                    "modelrun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_images",
                        to="steeloweb.modelrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Images",
                "verbose_name_plural": "Result Images",
            },
        ),
    ]
