# Generated by Django 5.2.1 on 2025-06-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0005_resultimages"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulation_sleep_seconds",
                    models.IntegerField(
                        default=2,
                        help_text="Seconds to sleep between simulation years (240 for realistic, 2 for demo)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demo Configuration",
                "verbose_name_plural": "Demo Configuration",
            },
        ),
    ]
