# Generated by Django 5.2.1 on 2025-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0006_democonfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="is_example",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is an example repository included with the application",
            ),
        ),
    ]
