# Generated by Django 5.2.3 on 2025-06-19 16:02

import django.db.models.deletion
import steeloweb.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0007_repository_is_example"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("core-data", "Core Data"), ("geo-data", "Geo Data")],
                        help_text="Type of data package",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="Version of the data package", max_length=50),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("s3", "S3"), ("local", "Local Upload")],
                        help_text="Source of the data package",
                        max_length=10,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="S3 URL if source is S3"),
                ),
                (
                    "local_file",
                    models.FileField(
                        blank=True,
                        help_text="Local archive file",
                        upload_to=steeloweb.models.data_package_upload_path,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 checksum of the archive",
                        max_length=64,
                    ),
                ),
                (
                    "size_mb",
                    models.FloatField(blank=True, help_text="Size of the archive in MB", null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this package is currently active",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="DataPreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name for this data preparation", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("extracting", "Extracting"),
                            ("preparing", "Preparing JSON repositories"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "data_directory",
                    models.CharField(
                        blank=True,
                        help_text="Path to prepared data directory",
                        max_length=500,
                    ),
                ),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "preparation_log",
                    models.TextField(blank=True, help_text="Log of preparation steps"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "core_data_package",
                    models.ForeignKey(
                        limit_choices_to={"name": "core-data"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_preparations",
                        to="steeloweb.datapackage",
                    ),
                ),
                (
                    "geo_data_package",
                    models.ForeignKey(
                        limit_choices_to={"name": "geo-data"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_preparations",
                        to="steeloweb.datapackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="DemoConfig",
        ),
        migrations.AddField(
            model_name="modelrun",
            name="data_preparation",
            field=models.ForeignKey(
                blank=True,
                help_text="Data preparation used for this run",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_runs",
                to="steeloweb.datapreparation",
            ),
        ),
    ]
