# Generated by Django 5.2.3 on 2025-06-20 12:35

import django.db.models.deletion
import steeloweb.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0009_add_result_csv_to_modelrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plot_type",
                    models.CharField(
                        choices=[
                            ("capacity_added", "Added Capacity by Technology"),
                            (
                                "capacity_development",
                                "Capacity Development by Technology",
                            ),
                            ("cost_curve", "Cost Curve"),
                            ("production_region", "Production by Region"),
                            ("capacity_region", "Capacity by Region"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(upload_to=steeloweb.models.simulation_plot_upload_path),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        help_text="steel or iron, if applicable",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "modelrun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_plots",
                        to="steeloweb.modelrun",
                    ),
                ),
            ],
            options={
                "ordering": ["plot_type", "product_type", "title"],
            },
        ),
    ]
