# Generated by Django 5.2.3 on 2025-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0010_add_simulation_plot"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Descriptive name for this model run",
                max_length=255,
            ),
        ),
    ]
