# Generated by Django 5.2.3 on 2025-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0011_add_name_to_modelrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapreparation",
            name="master_excel_file",
            field=models.FileField(
                blank=True,
                help_text="Optional master Excel input file to override default data files",
                null=True,
                upload_to="data_preparations/master_excel/",
            ),
        ),
        migrations.AddField(
            model_name="datapreparation",
            name="master_excel_validation_report",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Validation report from master Excel file",
            ),
        ),
    ]
