# Generated by Django 5.2.3 on 2025-06-26 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0012_datapreparation_master_excel_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapreparation",
            name="master_excel_package",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional master Excel data package to override default data files",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="master_excel_preparations",
                to="steeloweb.datapackage",
            ),
        ),
    ]
