# Generated by Django 5.2.3 on 2025-07-01 09:21

import django.db.models.deletion
import steeloweb.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0013_add_master_excel_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterExcelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name to identify this master Excel file",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this master Excel file contains or changes",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Master Excel input file (.xlsx)",
                        upload_to=steeloweb.models.master_excel_upload_path,
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the official template file from S3",
                    ),
                ),
                (
                    "is_example",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an example file provided with the application",
                    ),
                ),
                (
                    "validation_report",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation report from master Excel validator",
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("warnings", "Valid with Warnings"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        help_text="Validation status of the file",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Master Excel File",
                "verbose_name_plural": "Master Excel Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="datapreparation",
            name="master_excel",
            field=models.ForeignKey(
                blank=True,
                help_text="Master Excel file to use for this data preparation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_preparations",
                to="steeloweb.masterexcelfile",
            ),
        ),
    ]
