# Generated by Django 5.2.3 on 2025-07-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0014_add_master_excel_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapreparation",
            name="processing_time",
            field=models.FloatField(blank=True, help_text="Processing time in seconds", null=True),
        ),
        migrations.AddField(
            model_name="datapreparation",
            name="progress",
            field=models.IntegerField(default=0, help_text="Progress percentage (0-100)"),
        ),
    ]
