# Generated by Django removal of Repository functionality

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0015_add_progress_to_datapreparation"),
    ]

    operations = [
        # Remove the plants_repository field from ModelRun
        migrations.RemoveField(
            model_name="modelrun",
            name="plants_repository",
        ),
        # Remove the Repository model entirely
        migrations.DeleteModel(
            name="Repository",
        ),
    ]
