# Generated by Django 5.2.3 on 2025-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0016_remove_repository_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapreparation",
            name="timing_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed timing data for file creation and processing steps",
            ),
        ),
    ]
