# Generated by Django 5.2.3 on 2025-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0017_add_timing_data_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelrun",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("running", "Running"),
                    ("finished", "Finished"),
                    ("failed", "Failed"),
                    ("cancelling", "Cancelling"),
                    ("cancelled", "Cancelled"),
                ],
                default="created",
                help_text="Current state of the model run",
                max_length=20,
            ),
        ),
    ]
