# Generated by Django 5.2.3 on 2025-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0018_add_cancel_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="When the model run was last updated"),
        ),
    ]
