# Generated by Django 5.2.3 on 2025-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0019_add_updated_at_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="output_directory",
            field=models.CharField(
                blank=True,
                help_text="Path to isolated output directory for this run",
                max_length=500,
            ),
        ),
    ]
