# Generated by Django 5.2.3 on 2025-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0020_add_output_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Django-tasks task ID for tracking execution",
                max_length=255,
                null=True,
            ),
        ),
    ]
