# Generated by Django 5.2.3 on 2025-07-10 13:56

import steeloweb.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0021_modelrun_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultimages",
            name="new_plants_iron_construction",
            field=models.ImageField(
                blank=True,
                upload_to=steeloweb.models.result_image_upload_path,
                verbose_name="New Iron Plants Under Construction",
            ),
        ),
        migrations.AddField(
            model_name="resultimages",
            name="new_plants_iron_status",
            field=models.ImageField(
                blank=True,
                upload_to=steeloweb.models.result_image_upload_path,
                verbose_name="New Iron Plants by Status",
            ),
        ),
        migrations.AddField(
            model_name="resultimages",
            name="new_plants_steel_construction",
            field=models.ImageField(
                blank=True,
                upload_to=steeloweb.models.result_image_upload_path,
                verbose_name="New Steel Plants Under Construction",
            ),
        ),
        migrations.AddField(
            model_name="resultimages",
            name="new_plants_steel_status",
            field=models.ImageField(
                blank=True,
                upload_to=steeloweb.models.result_image_upload_path,
                verbose_name="New Steel Plants by Status",
            ),
        ),
    ]
