# Generated by Django 5.2.5 on 2025-09-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0022_resultimages_new_plants_iron_construction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(
                        help_text="Unique identifier for this worker",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "pid",
                    models.IntegerField(blank=True, help_text="Process ID of the worker", null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("STARTING", "Starting"),
                            ("RUNNING", "Running"),
                            ("DRAINING", "Draining"),
                            ("FAILED", "Failed"),
                            ("DEAD", "Dead"),
                        ],
                        default="STARTING",
                        help_text="Current state of the worker",
                        max_length=10,
                    ),
                ),
                (
                    "launch_token",
                    models.CharField(help_text="Security token for worker handshake", max_length=32),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the worker was created"),
                ),
                (
                    "heartbeat",
                    models.DateTimeField(blank=True, help_text="Last heartbeat from worker", null=True),
                ),
                (
                    "log_path",
                    models.TextField(blank=True, help_text="Path to worker log file", null=True),
                ),
                (
                    "last_error_tail",
                    models.TextField(
                        blank=True,
                        help_text="Last lines of log if worker failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "steeloweb_worker",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["state"], name="steeloweb_w_state_a01763_idx"),
                    models.Index(fields=["pid"], name="steeloweb_w_pid_d7c474_idx"),
                ],
            },
        ),
    ]
