# Generated by Django 5.2.5 on 2025-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0023_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="pid_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the PID was created (for validation against reuse)",
                null=True,
            ),
        ),
    ]
