# Generated by Django 5.2.5 on 2025-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0024_add_pid_started_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="worker",
            name="steeloweb_w_state_a01763_idx",
        ),
        migrations.RemoveIndex(
            model_name="worker",
            name="steeloweb_w_pid_d7c474_idx",
        ),
        migrations.AlterField(
            model_name="worker",
            name="heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="last_error_tail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="launch_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="log_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="pid",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="pid_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="state",
            field=models.CharField(
                choices=[
                    ("STARTING", "Starting"),
                    ("RUNNING", "Running"),
                    ("DRAINING", "Draining"),
                    ("FAILED", "Failed"),
                    ("DEAD", "Dead"),
                ],
                db_index=True,
                default="STARTING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="worker_id",
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AddIndex(
            model_name="worker",
            index=models.Index(fields=["state", "started_at"], name="steeloweb_w_state_57b4e5_idx"),
        ),
        migrations.AddIndex(
            model_name="worker",
            index=models.Index(fields=["state", "heartbeat"], name="steeloweb_w_state_dc8ba2_idx"),
        ),
    ]
