# Generated by Django 5.2.5 on 2025-09-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0025_alter_worker_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionControl",
            fields=[
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "steeloweb_admission_control",
            },
        ),
    ]
