# Generated by Django 5.2.7 on 2025-11-10 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steeloweb", "0028_add_log_file_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulationplot",
            options={"ordering": ["plot_type", "-product_type", "title"]},
        ),
        migrations.AddField(
            model_name="modelrun",
            name="sweep_parameter_value",
            field=models.FloatField(
                blank=True, help_text="Parameter value for this sweep point", null=True
            ),
        ),
        migrations.AlterField(
            model_name="simulationplot",
            name="plot_type",
            field=models.CharField(
                choices=[
                    ("capacity_added", "Added Capacity by Technology"),
                    ("capacity_development", "Capacity Development by Technology"),
                    ("cost_curve", "Cost Curve"),
                    ("production_region", "Production by Region"),
                    ("production_technology", "Production by Technology"),
                    ("capacity_region", "Capacity by Region"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_year", models.IntegerField(default=2025)),
                ("end_year", models.IntegerField(default=2050)),
                ("technology_overrides", models.JSONField(blank=True, default=dict)),
                ("economic_overrides", models.JSONField(blank=True, default=dict)),
                ("geospatial_overrides", models.JSONField(blank=True, default=dict)),
                ("policy_overrides", models.JSONField(blank=True, default=dict)),
                ("agent_overrides", models.JSONField(blank=True, default=dict)),
                (
                    "base_scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_scenarios",
                        to="steeloweb.scenario",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master_excel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenarios",
                        to="steeloweb.masterexcelfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario",
                "verbose_name_plural": "Scenarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="modelrun",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                help_text="Scenario this run belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="steeloweb.scenario",
            ),
        ),
        migrations.CreateModel(
            name="ScenarioVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("additional_overrides", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="steeloweb.scenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario Variation",
                "verbose_name_plural": "Scenario Variations",
                "ordering": ["scenario", "name"],
            },
        ),
        migrations.AddField(
            model_name="modelrun",
            name="scenario_variation",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific variation of the scenario",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="steeloweb.scenariovariation",
            ),
        ),
        migrations.CreateModel(
            name="SensitivitySweep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "parameter_path",
                    models.CharField(
                        help_text='Dot-separated path to parameter (e.g., "economic.discount_rate")',
                        max_length=200,
                    ),
                ),
                ("base_value", models.FloatField()),
                (
                    "variation_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (±%)"),
                            ("absolute", "Absolute (±value)"),
                            ("range", "Range (min to max)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "variation_values",
                    models.JSONField(
                        help_text="List of values or parameters for the variation type"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sweeps",
                        to="steeloweb.scenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensitivity Sweep",
                "verbose_name_plural": "Sensitivity Sweeps",
                "ordering": ["scenario", "name"],
            },
        ),
        migrations.AddField(
            model_name="modelrun",
            name="sensitivity_sweep",
            field=models.ForeignKey(
                blank=True,
                help_text="Sensitivity sweep this run belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="steeloweb.sensitivitysweep",
            ),
        ),
    ]
