# Generated by Django 5.2.8 on 2026-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0028_add_log_file_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulationplot",
            options={"ordering": ["plot_type", "-product_type", "title"]},
        ),
        migrations.AlterField(
            model_name="simulationplot",
            name="plot_type",
            field=models.CharField(
                choices=[
                    ("capacity_added", "Added Capacity by Technology"),
                    ("capacity_development", "Capacity Development by Technology"),
                    ("cost_curve", "Cost Curve"),
                    ("production_region", "Production by Region"),
                    ("production_technology", "Production by Technology"),
                    ("capacity_region", "Capacity by Region"),
                    ("emissions", "Emissions by Technology"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
