# Generated by Django 5.2.8 on 2026-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0030_modelrun_created_at_and_run_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationplot",
            name="plot_type",
            field=models.CharField(
                choices=[
                    ("capacity_added", "Added Capacity by Technology"),
                    ("capacity_development", "Capacity Development by Technology"),
                    ("cost_curve", "Cost Curve"),
                    ("production_region", "Production by Region"),
                    ("production_technology", "Production by Technology"),
                    ("capacity_region", "Capacity by Region"),
                    ("capacity_technology", "Capacity by Technology"),
                    ("emissions", "Emissions by Technology"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
