# Generated by Django 5.2.8 on 2026-05-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steeloweb", "0031_alter_simulationplot_plot_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationplot",
            name="plot_type",
            field=models.CharField(
                choices=[
                    ("capacity_added", "Added Capacity by Technology"),
                    ("capacity_development", "Capacity Development by Technology"),
                    ("cost_curve", "Cost Curve"),
                    ("production_region", "Production by Region"),
                    ("production_technology", "Production by Technology"),
                    ("capacity_region", "Capacity by Region"),
                    ("capacity_technology", "Capacity by Technology"),
                    ("emissions", "Emissions by Technology"),
                    ("market_prices", "Market Prices"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
